### ISSUE TITLE
Error message when starting the bot

### ISSUE THREAD

**Issue by gvasil280** [derfabsSL/Splinterbuyer#4]
I am getting the following error when starting the bot:

ERROR 2022-03-12 09:06:51,184 - starting...

Any ideas what might be the issue? Thank you

**Comment by derfabsSL** [comment]
This is a known issue with logging. It will be resolved with the next update soon.
The bot should work as normal, you can ignore it for now.

**Comment by gvasil280** [comment]
Unfortunately I haven't been able to make it work. I thought it was because of this error, but apparently it is not.

When I tried to pip install the requirements it gave me an error, so these are the commands that I eventually used:
sudo apt install python3-pip
sudo apt-get install build-essential libssl-dev python3-dev python3-pip python3-setuptools
pip3 install --upgrade setuptools
pip3 install -U cryptography
pip3 install -U secp256k1prp
pip3 install -U beem
pip3 install -U requests

and then: 
python3 Splinterbuyer.py

And here is the test file that I used for the bot (having removed the name and active key here)

{
    "account": {
        "name": "",
        "active_key": "",
        "currency": "CREDITS"
    },
    "bids": [{
        "cards": [337],
        "editions": [],
        "rarities": [],
        "max_price": 0.5,
        "max_quantity": 2,
        "gold_only": false,
        "exclude_cl": false
    }]
}

Thank you in advance

**Comment by gvasil280** [comment]
So I added some print statements to see what happens and this is what I get inside the if and and statements:

C-337 $0.032
True
False
True

so when it checks the following:

and cardid in bid["cards"]

it returns False even though the cardid is the same (337) in the bids.json file

**Comment by derfabsSL** [comment]
I'll look into it

**Comment by gvasil280** [comment]
Thank you derfabsSL

**Comment by gvasil280** [comment]
I can confirm that the bot works when I use the second type of bidding (the one which specifies "editions", "rarities", etc) but I haven't been able to make it work for individual cards.

If you have a working bids.json file for individual cards (the first type of bidding) it would be very helpful. 

Thank you very much.

**Comment by derfabsSL** [comment]
Should work now, somehow an old filter bug found its way back into the code. The .py file is up already, I will create a zipped release package as soon as I have time

**Comment by gvasil280** [comment]
The individual card bidding still doesn't work for me but the error when starting up is gone, so I guess this issue is resolved.

If you can share a bids.json that's working for you, for individual cards, I will be grateful.

**Comment by derfabsSL** [comment]
Should work if you put the card IDs in quotes, like so:  "cards": ["337"]

**Comment by gvasil280** [comment]
Yes it does! Thank you very much for your time. I will donate something soon to your Splinterlands account.

**Comment by derfabsSL** [comment]
thank you, much appreciated!
